### ISSUE TITLE
Events found in Natural Language

### ISSUE THREAD

**Issue by letsgorocket** [cbeardsmore/UpcomingEvents#2]
Hi @cbeardsmore,

Thank you for the wigets! I saw some upcoming events say "Found in Natural Language". Do you know how to remove the event "found in Natural Language"? I don't know where these events come from.

**Comment by cbeardsmore** [comment]
HI @letsgorocket, i'm currently working on updating the parser, which should make it a little more robust overall.

Is it possible for you to run the following command into terminal and copy and paste the output here as a comment:
    "icalBuddy -n eventsToday+2"

That should allow me to see what exactly is causing the issue to pop up (or email me if thats better).
Thanks!

**Comment by letsgorocket** [comment]
Thank you @cbeardsmore for the reply!! I screenshot my terminal here:

<img width="898" alt="screen shot 2018-02-14 at 10 55 44 am" src="https://user-images.githubusercontent.com/25697115/36216919-b9d35e58-1175-11e8-9fa9-052de55a009b.png">

**Comment by cbeardsmore** [comment]
It looks like the (Found in Natural Language) is the calendar that the task belongs to, it might just be getting automatically added by google when adding certain events.

Either way, the new version of the widget (updated on this repo) has a new flag SHOW_CALENDAR thtat can be set to 'true' or 'false'. Setting to 'false' will hide the calendar item from the events so only the event name is shown. The item parsing has also been improved so any issues with URL's and Note fields should be resolved. Thanks.

**Comment by letsgorocket** [comment]
Thank you @cbeardsmore ! Do you know how to only show specific calendar? For example, I don't want to see the event from my "Work" calendar.

**Comment by cbeardsmore** [comment]
That sounds like a good idea actually. I'll look into how feasible it is in filtering certain calendars out. Thanks for the idea and hopefully I can get it implemented soon.

**Comment by cbeardsmore** [comment]
Implemented, just need to put the name of the calendars to ignore in this list in the code.

```javascript
# Ignore specific calendars
IGNORE_CALENDER = [ 'name of calendar to ignore', 'other calendar etc' ]
```

**Comment by letsgorocket** [comment]
Thank you for updated!! I tried but it seems not work. Maybe somehow I did incorrectly. The calendar I ignored still there.
<img width="854" alt="screen shot 2018-02-18 at 3 07 29 pm" src="https://user-images.githubusercontent.com/25697115/36356844-9e838b50-14bd-11e8-8f28-fc01976afba3.png">
<img width="378" alt="screen shot 2018-02-18 at 3 07 39 pm" src="https://user-images.githubusercontent.com/25697115/36356847-9f9d003e-14bd-11e8-8580-b3c2d0e16ac8.png">

**Comment by cbeardsmore** [comment]
Hmmm. What happens if you put a space after the claendar name in IGNORE CALENDER,
So 'Found in Natural Language ' <-- space right at the end.
I'll have another look into it! It's hard to test and get a universal solution when everyones calendars are slightly different 🙃

**Comment by letsgorocket** [comment]
Still no work. lol Thank you so much for answering my question!!
